name: CIFuzz

on:
  push:
    paths-ignore:
    - '.actions/**'
    - '.gitattributes'
    - '.gitignore'
    - 'LICENSE'
    - 'NEWS'
    - '**.adoc'
    - '**.css'
    - 'examples/**'
    - 'man/**'
    - 'regress/**'
    - 'src/hid_*.c'
    - '!src/hid_linux.c'
    - '!src/hid_unix.c'
    - 'tools/**'
    - 'udev/**'
    - 'windows/**'
  pull_request:
    paths-ignore:
    - '.actions/**'
    - '.gitattributes'
    - '.gitignore'
    - 'LICENSE'
    - 'NEWS'
    - '**.adoc'
    - '**.css'
    - 'examples/**'
    - 'man/**'
    - 'regress/**'
    - 'src/hid_*.c'
    - '!src/hid_linux.c'
    - '!src/hid_unix.c'
    - 'tools/**'
    - 'udev/**'
    - 'windows/**'

jobs:
  Fuzzing:
    if: github.repository == 'Yubico/libfido2'
    runs-on: ubuntu-latest
    steps:
    - name: Build Fuzzers
      uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@master
      with:
        oss-fuzz-project-name: 'libfido2'
        dry-run: false
    - name: Run Fuzzers
      uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@master
      with:
        oss-fuzz-project-name: 'libfido2'
        fuzz-seconds: 600
        dry-run: false
    - name: Upload Crash
      uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: artifacts
        path: ./out/artifacts
