name: macos

on:
  push:
    paths-ignore:
    - '.actions/**'
    - '!.actions/build-osx-clang'
    - '.gitattributes'
    - '.gitignore'
    - 'LICENSE'
    - 'NEWS'
    - '**.adoc'
    - '**.css'
    - 'fuzz/**'
    - 'src/hid_*.c'
    - '!src/hid_osx.c'
    - '!src/hid_unix.c'
    - 'src/netlink.c'
    - 'src/nfc_linux.c'
    - 'udev/**'
    - 'windows/**'
  pull_request:
    paths-ignore:
    - '.actions/**'
    - '!.actions/build-osx-clang'
    - '.gitattributes'
    - '.gitignore'
    - 'LICENSE'
    - 'NEWS'
    - '**.adoc'
    - '**.css'
    - 'fuzz/**'
    - 'src/hid_*.c'
    - '!src/hid_osx.c'
    - '!src/hid_unix.c'
    - 'src/netlink.c'
    - 'src/nfc_linux.c'
    - 'udev/**'
    - 'windows/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        cc: [clang]
    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: brew install libcbor llvm mandoc pkg-config
    - name: build
      env:
        CC: ${{ matrix.cc }}
      run: ./.actions/build-osx-clang
