name: windows

on:
  push:
    paths-ignore:
    - '.actions/**'
    - '.gitattributes'
    - '.gitignore'
    - 'LICENSE'
    - 'NEWS'
    - '**.adoc'
    - '**.css'
    - 'fuzz/**'
    - 'man/**'
    - 'src/hid_*.c'
    - '!src/hid_win.c'
    - 'src/netlink.c'
    - 'src/nfc_linux.c'
    - 'udev/**'
  pull_request:
    paths-ignore:
    - '.actions/**'
    - '.gitattributes'
    - '.gitignore'
    - 'LICENSE'
    - 'NEWS'
    - '**.adoc'
    - '**.css'
    - 'fuzz/**'
    - 'man/**'
    - 'src/hid_*.c'
    - '!src/hid_win.c'
    - 'src/netlink.c'
    - 'src/nfc_linux.c'
    - 'udev/**'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: .\windows\build.ps1
